//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2Basic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int CustomerID { get; set; }
        public string UserID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
