//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2Basic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public string TransactionType { get; set; }
        public int AccountNumber { get; set; }
        public Nullable<int> DestAccount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
